# Generated by Django 2.1.5 on 2019-02-03 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Businfo',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('bname', models.CharField(max_length=50)),
                ('uptime', models.CharField(blank=True, max_length=50, null=True)),
                ('dwtime', models.CharField(blank=True, max_length=50, null=True)),
                ('price', models.CharField(blank=True, max_length=50, null=True)),
                ('company', models.CharField(blank=True, max_length=50, null=True)),
                ('updata', models.CharField(blank=True, max_length=32, null=True)),
                ('upcount', models.CharField(blank=True, max_length=32, null=True)),
                ('upsite', models.CharField(blank=True, max_length=500, null=True)),
                ('dwcount', models.CharField(blank=True, max_length=32, null=True)),
                ('dwsite', models.CharField(blank=True, max_length=500, null=True)),
            ],
            options={
                'db_table': 'businfo',
                'managed': False,
            },
        ),
    ]
